apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app: postgres-sts
spec:
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
  clusterIP: None
  selector:
    app: postgres-stsc