apiVersion: v1
kind: Pod
metadata:
  name: postgresql
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        # Define the environment variable
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: config-map   
              key: postgres-user

        - name: POSTGRES_DBNAME
          valueFrom:
            configMapKeyRef:
              name: config-map   
              key: postgres-db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret   
              key: postgres-pass